title: <p align="center"> Amrita Roy </p>
logo: /assets/img/logo1.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/amrita-roy-b0245390/">LinkedIn</a> |
  <a href="https://github.com/royamrita23">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
