title: <p align="center"> Amrita Roy </p>
logo: /assets/img/logo1.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/amrita-roy-b0245390/">LinkedIn</a> |
  <a href="https://github.com/royamrita23">GitHub</a>
  
  <br>   
  I am working as Geoscientist in Oil India Limited for 5 years
  currently Studing Executive PG Diploma on Data Science in upGrad + IIITB
  <br>
  </p>




theme: jekyll-theme-minimal
